project:
  name: 'sustainable-finance-trends'
  filename: 'sustainable_finance'
  analysis_file: 'esg_trends_analysis'
dir:
  root: './'
  root_pipeline: '../'
  pipeline: 'pipelines'
  raw_data: 'data/0_external'
  interim_data: 'data/1_interim'
  final_data: 'data/2_final'
query:
  geo: global
  top_n: 35
  kw_list: [
    "sustainable investment", 
    "ESG", 
    "sustainable finance", 
    "responsible investment"
  ]
  blacklist: [
    "esg gold", 
    "esg glas", 
    "esg tours", 
    "esg surgery", 
    "esg skyline", 
    "esg tour mykonos", 
    "esg movies", 
    "esg mobility", 
    "esg nerdl", 
    "gold", 
    "esg secure p8b"
    ]   
  uppercase: [
    "ESG", 
    "SDG", 
    "ETF", 
    "MSCI", 
    "SRI", 
    "ICICI", 
    "SBI", 
    "PEI", 
    "SFDR", 
    "EU ", 
    "ISS ", 
    "TCFD", 
    "HLEG", 
    "EBA ", 
    "TEG ", 
    "IPSF", 
    "GPIF"
    ]
app: 
  rename: {'query': 'Keyword', 
        "rank_t": "Rank",
        'rank_t-1': "Previous rank", 
        'keyword': 'Topic', 
        'value': 'Raw Google Trends value', 
        'query_date': 'Date', 
        'rank_absolute_change': 'Change in ranking', 
        'new_entry_t': 'New this period',
        'dropout_t+1': 'Dropout next period'}

