project:
  name: 'sustainable-finance-trends'
  filename: 'sustainable_finance'
  analysis_file: 'esg_trends_analysis'
dir:
  root: '../'
  pipeline: 'pipelines'
  raw_data: 'data/0_external'
  interim_data: 'data/1_interim'
  final_data: 'data/2_final'
query:
  geo: global
  top_n: 35
  kw_list: [
    "sustainable investment", 
    "ESG", 
    "sustainable finance", 
    "responsible investment"
  ]
  blacklist: [
    "esg gold", 
    "esg glas", 
    "esg tours", 
    "esg surgery", 
    "esg skyline", 
    "esg tour mykonos", 
    "esg movies", 
    "esg mobility", 
    "esg nerdl", 
    "gold"
    ]   
  uppercase: [
    "ESG", 
    "SDG", 
    "ETF", 
    "MSCI", 
    "SRI", 
    "ICICI", 
    "SBI", 
    "PEI", 
    "SFDR", 
    "EU ", 
    "ISS ", 
    "TCFD", 
    "HLEG", 
    "EBA "
    ]



# [data-science-trends]
# DATA_DIR = C:/Users\phili\Google Drive\Projekter\Google keywords\esg_trending_topics\data\0_external
# FILE_NAME = data_science
# KW_LIST = ["data science", "machine learning", "deep learning", "artificial intelligence", "ai"], 
# GEO = global
# TOP_N = 35